In [83]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split

ValueError: Unknown label type: continuous-multioutput. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [159]:
# model for the prediction of the position of satellite based on the features and provided tles 
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split


data=np.load("features.npy")
features=pd.DataFrame(data)


df=np.load("outputs.npy")
san=pd.DataFrame(df)

x_y_z_test=pd.DataFrame(df)
x_y_z_test.columns=["x","y","z"]
x_y_z=features.iloc[:,-1:-4:-1].iloc[:,-1:-4:-1]
x_y_z.columns=["x","y","z"]
y = x_y_z  
x = features.iloc[:,:27]  


model = RandomForestRegressor(n_estimators=25, random_state=33)
model.fit(x,y)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

predicted=model.predict(x_test)

predicted.shape
actual=np.array(y_test)
predicteed=np.array(predicted)


# saving the file as .npy 

np.save("actual.npy",actual)
np.save("predicted",predicteed)

#analysis over error associated 
r2=r2_score(y_test,predicted)

mse=mean_squared_error(y_test,predicted)
rmse=np.sqrt(mse)
print("R2_score",r2)
print("rmse",rmse)


R2_score 0.9996056706221411
rmse 27.70096287563592


x            y            z
0    1518.470044  2214.896098  6459.191555
1     436.817923 -2097.153763  6647.933042
2    -821.195902 -5558.795485  4139.251606
3   -1744.657698 -6757.442136   -57.176001
4   -1956.756250 -5200.632898 -4230.563562
..           ...          ...          ...
706   736.366730  6516.512291 -2486.914940
707  1383.505103  6601.516775  1905.718692
708  1473.360563  4027.792659  5528.271684
709   968.822595  -170.412060  6914.321998
710    72.420755 -4298.307928  5494.925655

[711 rows x 3 columns]

[[ 4.85635202e+01 -3.63026054e+03  5.96172962e+03]
 [-4.85328000e+02  2.19107031e+03 -6.63363413e+03]
 [-2.43813534e+02  3.55507276e+03 -6.03476757e+03]
 [-1.49255409e+03 -4.08344493e+03 -5.47310562e+03]
 [ 1.15601745e+03  9.33229137e+02  6.82776787e+03]
 [ 1.77553267e+03  4.94207966e+03  4.63273294e+03]
 [ 1.51795275e+03  3.02290802e+03  6.12306359e+03]
 [-4.90299690e+01 -3.79706241e+03  5.85730277e+03]
 [ 3.90929059e+02  4.73788914e+03 -5.14928239e+03]
 [-8.08010266e+02 -6.11040994e+03  3.26982029e+03]
 [ 9.61734467e+02 -2.07621911e+02  6.91719033e+03]
 [-1.63510979e+03 -6.24637316e+03 -2.65715302e+03]
 [ 1.77685079e+03  6.34769923e+03  2.38199228e+03]
 [ 7.24247010e+02 -1.12475832e+03  6.85693440e+03]
 [ 7.24207548e+01 -4.29830793e+03  5.49492565e+03]
 [ 1.53745384e+03  3.66094268e+03  5.76084637e+03]
 [-1.46673252e+03 -3.02392047e+03 -6.13086634e+03]
 [-3.66553568e+02  3.11158648e+03 -6.26804347e+03]
 [-1.48987313e+03 -6.52406010e+03 -1.98920840e+03]
 [-1.62377087e+03 -6.78565261e+

UnpicklingError: Failed to interpret file 'actual.npy' as a pickle

In [97]:
b

array([[  185.77145972, -3546.59320384,  6007.52053255],
       [ -558.45762084,  1995.48062463, -6689.53163482],
       [  -62.2077322 ,  3554.07705731, -6037.03125501],
       [-1702.05629075, -4012.37434772, -5461.7560641 ],
       [ 1193.06067365,  1014.81535269,  6811.13644773],
       [ 1673.12572728,  4904.32287357,  4708.89540349],
       [ 1591.97300842,  3084.41691468,  6074.78751433],
       [  -99.3354054 , -4044.5134154 ,  5687.64430185],
       [  189.57833618,  4130.03309285, -5656.65483949],
       [ -824.069016  , -6247.71674577,  2994.30368702],
       [ 1054.91451823,   167.72584952,  6907.22885283],
       [-1873.96714894, -6260.24853655, -2457.01732451],
       [ 1898.22631789,  6348.28385537,  2286.02937246],
       [  780.30343393, -1183.76485409,  6836.57657768],
       [ -122.757732  , -4600.96923795,  5244.10156535],
       [ 1508.10476779,  3846.27875596,  5646.80281294],
       [-1550.8114007 , -2491.47528471, -6344.29765837],
       [ -244.54932591,  3204.2